### PR TITLE
ManagerProvider

### PR DESCRIPTION
**Pull request by bilalb**

### CODE REVIEW

**Comment by zarghol** [comment]
Yes I meant that :) okay I knew these advantages, but not worth it for me : how can you mock this ? One mock a single manager in the instance of your singleton ? That’s the advantage of decentralized managers :) + not all managers in the same basket :P

**Comment by zarghol** [comment]
Yes I meant that :) okay I knew these advantages, but not worth it for me : how can you mock this ? One mock a single manager in the instance of your singleton ? That’s the advantage of decentralized managers :) + not all managers in the same basket :P

**Comment by zarghol** [comment]
What do you want to do with this MR ? :)

**Comment by bilalb** [comment]
> What do you want to do with this MR ? :)

I'll close it, because I think it's not relevant :)

**Pull request closed without merging**
